// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-friends.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.103.0";
function supabaseForUser(ctx) {
  const url = process.env.SUPABASE_URL;
  const key = process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY;
  return createClient(url, key, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-friends.ts
var list_friends_default = defineTool({
  name: "list_friends",
  title: "List friends",
  description: "List the signed-in user's accepted friends on Drop.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const uid = ctx.getUserId();
    const { data, error } = await supabase.from("friendships").select("requester_id, addressee_id, status, created_at").eq("status", "accepted").or(`requester_id.eq.${uid},addressee_id.eq.${uid}`);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    const friendIds = (data ?? []).map(
      (r) => r.requester_id === uid ? r.addressee_id : r.requester_id
    );
    if (friendIds.length === 0) {
      return { content: [{ type: "text", text: "No friends yet." }], structuredContent: { friends: [] } };
    }
    const { data: profiles, error: pErr } = await supabase.from("profiles").select("id, username, display_name, avatar_url").in("id", friendIds);
    if (pErr) {
      return { content: [{ type: "text", text: pErr.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(profiles) }],
      structuredContent: { friends: profiles ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-moments.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^4.4.3";
var list_moments_default = defineTool2({
  name: "list_moments",
  title: "List active Drops (Moments)",
  description: "List currently active Drops (Moments) visible to the signed-in user \u2014 their own and accepted friends'. RLS enforces visibility.",
  inputSchema: {
    limit: z.number().int().min(1).max(100).default(50).describe("Max rows to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("moments").select("id, creator_id, title, latitude, longitude, expires_at, created_at").gt("expires_at", (/* @__PURE__ */ new Date()).toISOString()).order("created_at", { ascending: false }).limit(limit);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { moments: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/create-moment.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^4.4.3";
var CAMPUS_SPOTS = {
  usdan: { name: "Usdan Student Center", lat: 42.3661, lng: -71.2589 },
  shapiro: { name: "Shapiro Campus Center", lat: 42.3667, lng: -71.2595 },
  goldfarb: { name: "Goldfarb Library", lat: 42.3659, lng: -71.2601 },
  gosman: { name: "Gosman Sports Center", lat: 42.3676, lng: -71.2611 },
  sherman: { name: "Sherman Dining", lat: 42.3648, lng: -71.2585 },
  great_lawn: { name: "Great Lawn", lat: 42.3655, lng: -71.2597 },
  chapels_field: { name: "Chapels Field", lat: 42.3671, lng: -71.2582 },
  massell: { name: "Massell Quad", lat: 42.3645, lng: -71.2593 },
  north_quad: { name: "North Quad", lat: 42.3672, lng: -71.2599 },
  skyline: { name: "Skyline Commons", lat: 42.3679, lng: -71.2578 },
  einstein: { name: "Einstein Bros", lat: 42.3663, lng: -71.2592 },
  moody: { name: "Moody Street", lat: 42.376, lng: -71.2358 },
  south_street: { name: "South Street", lat: 42.3641, lng: -71.2575 }
};
var create_moment_default = defineTool3({
  name: "create_moment",
  title: "Create a Drop (Moment)",
  description: "Create a Drop (Moment) \u2014 a plan at a Brandeis campus spot that expires after a set number of minutes. Visible to accepted friends per RLS.",
  inputSchema: {
    title: z2.string().trim().min(1).max(80).describe("Short plan title, e.g. 'Coffee at Einstein'."),
    spot: z2.enum(
      Object.keys(CAMPUS_SPOTS)
    ).describe("Brandeis campus spot key."),
    duration_minutes: z2.number().int().min(15).max(240).default(90).describe("How long the Drop stays live (15\u2013240 minutes).")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ title, spot, duration_minutes }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const s = CAMPUS_SPOTS[spot];
    const expiresAt = new Date(Date.now() + duration_minutes * 6e4).toISOString();
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("moments").insert({
      creator_id: ctx.getUserId(),
      title,
      latitude: s.lat,
      longitude: s.lng,
      expires_at: expiresAt
    }).select().single();
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [
        { type: "text", text: `Drop created at ${s.name}, expires ${expiresAt}.` }
      ],
      structuredContent: { moment: data, spot: s.name }
    };
  }
});

// src/lib/mcp/tools/list-pings.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^4.4.3";
var list_pings_default = defineTool4({
  name: "list_pings",
  title: "List received pings",
  description: "List pings received by the signed-in user, most recent first.",
  inputSchema: {
    unread_only: z3.boolean().default(false).describe("If true, return only unread pings."),
    limit: z3.number().int().min(1).max(100).default(50)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ unread_only, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("pings").select("id, sender_id, recipient_id, message, latitude, longitude, read, created_at").eq("recipient_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(limit);
    if (unread_only) query = query.eq("read", false);
    const { data, error } = await query;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { pings: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/send-ping.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z4 } from "npm:zod@^4.4.3";
var send_ping_default = defineTool5({
  name: "send_ping",
  title: "Send a ping",
  description: "Send a lightweight ping (nudge) to an accepted friend on Drop. RLS enforces that the recipient must be a friend.",
  inputSchema: {
    recipient_id: z4.string().uuid().describe("Profile id of the friend to ping."),
    message: z4.string().trim().max(200).optional().describe("Optional short message.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ recipient_id, message }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("pings").insert({
      sender_id: ctx.getUserId(),
      recipient_id,
      message: message ?? null
    }).select().single();
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: "Ping sent." }],
      structuredContent: { ping: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "yvkvgioomosldtjszdtk";
var mcp_default = defineMcp({
  name: "drop-mcp",
  title: "Drop",
  version: "0.1.0",
  instructions: "Tools for Drop, a Brandeis-only social plans app. Read the signed-in user's friends, active Drops (Moments), and pings, create new Drops at named campus spots, and send pings to accepted friends. All data is scoped to the signed-in user via Supabase RLS.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    list_friends_default,
    list_moments_default,
    create_moment_default,
    list_pings_default,
    send_ping_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
